# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'misc/important.ui'
#
# Created by: PyQt5 UI code generator 5.13.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(751, 590)
        self.gridLayoutWidget = QtWidgets.QWidget(Form)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(0, 0, 751, 591))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.checkBox_24 = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.checkBox_24.setObjectName("checkBox_24")
        self.gridLayout.addWidget(self.checkBox_24, 3, 5, 1, 1)
        self.checkBox_25 = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.checkBox_25.setObjectName("checkBox_25")
        self.gridLayout.addWidget(self.checkBox_25, 4, 0, 1, 1)
        self.checkBox_32 = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.checkBox_32.setObjectName("checkBox_32")
        self.gridLayout.addWidget(self.checkBox_32, 5, 1, 1, 1)
        self.checkBox_29 = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.checkBox_29.setObjectName("checkBox_29")
        self.gridLayout.addWidget(self.checkBox_29, 4, 4, 1, 1)
        self.checkBox_31 = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.checkBox_31.setObjectName("checkBox_31")
        self.gridLayout.addWidget(self.checkBox_31, 5, 0, 1, 1)
        self.checkBox_30 = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.checkBox_30.setObjectName("checkBox_30")
        self.gridLayout.addWidget(self.checkBox_30, 4, 5, 1, 1)
        self.checkBox_28 = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.checkBox_28.setObjectName("checkBox_28")
        self.gridLayout.addWidget(self.checkBox_28, 4, 3, 1, 1)
        self.checkBox_36 = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.checkBox_36.setObjectName("checkBox_36")
        self.gridLayout.addWidget(self.checkBox_36, 5, 5, 1, 1)
        self.checkBox_34 = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.checkBox_34.setObjectName("checkBox_34")
        self.gridLayout.addWidget(self.checkBox_34, 5, 3, 1, 1)
        self.checkBox_37 = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.checkBox_37.setObjectName("checkBox_37")
        self.gridLayout.addWidget(self.checkBox_37, 0, 6, 1, 1)
        self.checkBox_33 = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.checkBox_33.setObjectName("checkBox_33")
        self.gridLayout.addWidget(self.checkBox_33, 5, 2, 1, 1)
        self.checkBox_35 = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.checkBox_35.setObjectName("checkBox_35")
        self.gridLayout.addWidget(self.checkBox_35, 5, 4, 1, 1)
        self.checkBox_26 = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.checkBox_26.setObjectName("checkBox_26")
        self.gridLayout.addWidget(self.checkBox_26, 4, 1, 1, 1)
        self.checkBox_27 = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.checkBox_27.setObjectName("checkBox_27")
        self.gridLayout.addWidget(self.checkBox_27, 4, 2, 1, 1)
        self.checkBox_20 = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.checkBox_20.setObjectName("checkBox_20")
        self.gridLayout.addWidget(self.checkBox_20, 3, 1, 1, 1)
        self.checkBox_23 = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.checkBox_23.setObjectName("checkBox_23")
        self.gridLayout.addWidget(self.checkBox_23, 3, 4, 1, 1)
        self.checkBox_18 = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.checkBox_18.setObjectName("checkBox_18")
        self.gridLayout.addWidget(self.checkBox_18, 2, 5, 1, 1)
        self.checkBox_19 = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.checkBox_19.setObjectName("checkBox_19")
        self.gridLayout.addWidget(self.checkBox_19, 3, 0, 1, 1)
        self.checkBox_17 = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.checkBox_17.setObjectName("checkBox_17")
        self.gridLayout.addWidget(self.checkBox_17, 2, 4, 1, 1)
        self.checkBox_21 = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.checkBox_21.setObjectName("checkBox_21")
        self.gridLayout.addWidget(self.checkBox_21, 3, 2, 1, 1)
        self.checkBox_14 = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.checkBox_14.setObjectName("checkBox_14")
        self.gridLayout.addWidget(self.checkBox_14, 2, 1, 1, 1)
        self.checkBox_16 = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.checkBox_16.setObjectName("checkBox_16")
        self.gridLayout.addWidget(self.checkBox_16, 2, 3, 1, 1)
        self.checkBox_15 = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.checkBox_15.setObjectName("checkBox_15")
        self.gridLayout.addWidget(self.checkBox_15, 2, 2, 1, 1)
        self.checkBox_11 = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.checkBox_11.setObjectName("checkBox_11")
        self.gridLayout.addWidget(self.checkBox_11, 1, 4, 1, 1)
        self.checkBox_13 = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.checkBox_13.setObjectName("checkBox_13")
        self.gridLayout.addWidget(self.checkBox_13, 2, 0, 1, 1)
        self.checkBox_10 = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.checkBox_10.setObjectName("checkBox_10")
        self.gridLayout.addWidget(self.checkBox_10, 1, 3, 1, 1)
        self.checkBox_12 = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.checkBox_12.setObjectName("checkBox_12")
        self.gridLayout.addWidget(self.checkBox_12, 1, 5, 1, 1)
        self.checkBox = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.checkBox.setObjectName("checkBox")
        self.gridLayout.addWidget(self.checkBox, 0, 0, 1, 1)
        self.checkBox_22 = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.checkBox_22.setObjectName("checkBox_22")
        self.gridLayout.addWidget(self.checkBox_22, 3, 3, 1, 1)
        self.checkBox_6 = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.checkBox_6.setObjectName("checkBox_6")
        self.gridLayout.addWidget(self.checkBox_6, 0, 5, 1, 1)
        self.checkBox_5 = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.checkBox_5.setObjectName("checkBox_5")
        self.gridLayout.addWidget(self.checkBox_5, 0, 4, 1, 1)
        self.checkBox_7 = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.checkBox_7.setObjectName("checkBox_7")
        self.gridLayout.addWidget(self.checkBox_7, 1, 0, 1, 1)
        self.checkBox_2 = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.checkBox_2.setObjectName("checkBox_2")
        self.gridLayout.addWidget(self.checkBox_2, 0, 1, 1, 1)
        self.checkBox_4 = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.checkBox_4.setObjectName("checkBox_4")
        self.gridLayout.addWidget(self.checkBox_4, 0, 3, 1, 1)
        self.checkBox_3 = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.checkBox_3.setObjectName("checkBox_3")
        self.gridLayout.addWidget(self.checkBox_3, 0, 2, 1, 1)
        self.checkBox_9 = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.checkBox_9.setObjectName("checkBox_9")
        self.gridLayout.addWidget(self.checkBox_9, 1, 2, 1, 1)
        self.checkBox_8 = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.checkBox_8.setObjectName("checkBox_8")
        self.gridLayout.addWidget(self.checkBox_8, 1, 1, 1, 1)
        self.ok_ = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.ok_.setObjectName("ok_")
        self.gridLayout.addWidget(self.ok_, 6, 3, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.checkBox_24.setText(_translate("Form", "Астрономия"))
        self.checkBox_25.setText(_translate("Form", "Геометрия"))
        self.checkBox_32.setText(_translate("Form", "Род. Литература"))
        self.checkBox_29.setText(_translate("Form", "Черчение"))
        self.checkBox_31.setText(_translate("Form", "Информатика"))
        self.checkBox_30.setText(_translate("Form", "НВП"))
        self.checkBox_28.setText(_translate("Form", "Математика"))
        self.checkBox_36.setText(_translate("Form", "МХК"))
        self.checkBox_34.setText(_translate("Form", "Музыка"))
        self.checkBox_37.setText(_translate("Form", "Риторика"))
        self.checkBox_33.setText(_translate("Form", "Химия"))
        self.checkBox_35.setText(_translate("Form", "Естествознание"))
        self.checkBox_26.setText(_translate("Form", "ОБЖ"))
        self.checkBox_27.setText(_translate("Form", "Фин. Грамотность"))
        self.checkBox_20.setText(_translate("Form", "Обществознание"))
        self.checkBox_23.setText(_translate("Form", "Граждановедение"))
        self.checkBox_18.setText(_translate("Form", "Экология"))
        self.checkBox_19.setText(_translate("Form", "География"))
        self.checkBox_17.setText(_translate("Form", "Краеведение"))
        self.checkBox_21.setText(_translate("Form", "Физкультура"))
        self.checkBox_14.setText(_translate("Form", "Доп.Ин.яз."))
        self.checkBox_16.setText(_translate("Form", "Технология"))
        self.checkBox_15.setText(_translate("Form", "Физика"))
        self.checkBox_11.setText(_translate("Form", "ОРКЭС"))
        self.checkBox_13.setText(_translate("Form", "Биология"))
        self.checkBox_10.setText(_translate("Form", "Чтение"))
        self.checkBox_12.setText(_translate("Form", "Философия"))
        self.checkBox.setText(_translate("Form", "Алгебра"))
        self.checkBox_22.setText(_translate("Form", "Окр. Мир"))
        self.checkBox_6.setText(_translate("Form", "Правоведение"))
        self.checkBox_5.setText(_translate("Form", "ИЗО"))
        self.checkBox_7.setText(_translate("Form", "Ин.яз."))
        self.checkBox_2.setText(_translate("Form", "История"))
        self.checkBox_4.setText(_translate("Form", "Чистописание"))
        self.checkBox_3.setText(_translate("Form", "Родной язык"))
        self.checkBox_9.setText(_translate("Form", "Русский язык"))
        self.checkBox_8.setText(_translate("Form", "Литература"))
        self.ok_.setText(_translate("Form", "ОК"))
