# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'misc/stools.ui'
#
# Created by: PyQt5 UI code generator 5.13.1
#
# WARNING! All changes made in this file will be lost!


# Интерфейс класса STools
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 800, 600))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.tabWidget.setFont(font)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_mid = QtWidgets.QWidget()
        self.tab_mid.setObjectName("tab_mid")
        self.middle = QtWidgets.QLabel(self.tab_mid)
        self.middle.setGeometry(QtCore.QRect(0, 0, 800, 161))
        self.middle.setObjectName("middle")
        self._5 = QtWidgets.QPushButton(self.tab_mid)
        self._5.setGeometry(QtCore.QRect(12, 240, 250, 100))
        font = QtGui.QFont()
        font.setPointSize(36)
        self._5.setFont(font)
        self._5.setObjectName("_5")
        self._4 = QtWidgets.QPushButton(self.tab_mid)
        self._4.setGeometry(QtCore.QRect(272, 240, 250, 100))
        font = QtGui.QFont()
        font.setPointSize(36)
        self._4.setFont(font)
        self._4.setObjectName("_4")
        self._3 = QtWidgets.QPushButton(self.tab_mid)
        self._3.setGeometry(QtCore.QRect(532, 240, 250, 100))
        font = QtGui.QFont()
        font.setPointSize(36)
        self._3.setFont(font)
        self._3.setObjectName("_3")
        self._2 = QtWidgets.QPushButton(self.tab_mid)
        self._2.setGeometry(QtCore.QRect(137, 360, 250, 100))
        font = QtGui.QFont()
        font.setPointSize(36)
        self._2.setFont(font)
        self._2.setObjectName("_2")
        self._1 = QtWidgets.QPushButton(self.tab_mid)
        self._1.setGeometry(QtCore.QRect(397, 360, 250, 100))
        font = QtGui.QFont()
        font.setPointSize(36)
        self._1.setFont(font)
        self._1.setObjectName("_1")
        self.list = QtWidgets.QLabel(self.tab_mid)
        self.list.setGeometry(QtCore.QRect(0, 161, 800, 71))
        self.list.setObjectName("list")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.tab_mid)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(0, 470, 791, 80))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.clear_ = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.clear_.setFont(font)
        self.clear_.setObjectName("clear_")
        self.horizontalLayout.addWidget(self.clear_)
        self.delete_ = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.delete_.setFont(font)
        self.delete_.setObjectName("delete_")
        self.horizontalLayout.addWidget(self.delete_)
        self.save_ = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.save_.setFont(font)
        self.save_.setObjectName("save_")
        self.horizontalLayout.addWidget(self.save_)
        self.import_ = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.import_.setObjectName("import_")
        self.horizontalLayout.addWidget(self.import_)
        self.tabWidget.addTab(self.tab_mid, "")
        self.tab_lessons = QtWidgets.QWidget()
        self.tab_lessons.setObjectName("tab_lessons")
        self.label = QtWidgets.QLabel(self.tab_lessons)
        self.label.setGeometry(QtCore.QRect(0, 10, 800, 30))
        self.label.setObjectName("label")
        self.l_monday = QtWidgets.QLabel(self.tab_lessons)
        self.l_monday.setGeometry(QtCore.QRect(60, 40, 150, 30))
        self.l_monday.setObjectName("l_monday")
        self.l_tuesday = QtWidgets.QLabel(self.tab_lessons)
        self.l_tuesday.setGeometry(QtCore.QRect(320, 40, 150, 30))
        self.l_tuesday.setObjectName("l_tuesday")
        self.l_wednesday = QtWidgets.QLabel(self.tab_lessons)
        self.l_wednesday.setGeometry(QtCore.QRect(569, 40, 181, 30))
        self.l_wednesday.setObjectName("l_wednesday")
        self.l_thursday = QtWidgets.QLabel(self.tab_lessons)
        self.l_thursday.setGeometry(QtCore.QRect(60, 270, 150, 30))
        self.l_thursday.setObjectName("l_thursday")
        self.l_friday = QtWidgets.QLabel(self.tab_lessons)
        self.l_friday.setGeometry(QtCore.QRect(320, 270, 150, 30))
        self.l_friday.setObjectName("l_friday")
        self.l_saturday = QtWidgets.QLabel(self.tab_lessons)
        self.l_saturday.setGeometry(QtCore.QRect(610, 270, 111, 30))
        self.l_saturday.setObjectName("l_saturday")
        self.t_monday = QtWidgets.QTableWidget(self.tab_lessons)
        self.t_monday.setGeometry(QtCore.QRect(60, 70, 151, 192))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.t_monday.sizePolicy().hasHeightForWidth())
        self.t_monday.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.t_monday.setFont(font)
        self.t_monday.setMouseTracking(False)
        self.t_monday.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.t_monday.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.t_monday.setObjectName("t_monday")
        self.t_monday.setColumnCount(1)
        self.t_monday.setRowCount(7)
        item = QtWidgets.QTableWidgetItem()
        self.t_monday.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.t_monday.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.t_monday.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.t_monday.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.t_monday.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.t_monday.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.t_monday.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.t_monday.setHorizontalHeaderItem(0, item)
        self.t_tuesday = QtWidgets.QTableWidget(self.tab_lessons)
        self.t_tuesday.setGeometry(QtCore.QRect(320, 70, 151, 192))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.t_tuesday.sizePolicy().hasHeightForWidth())
        self.t_tuesday.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.t_tuesday.setFont(font)
        self.t_tuesday.setMouseTracking(False)
        self.t_tuesday.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.t_tuesday.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.t_tuesday.setObjectName("t_tuesday")
        self.t_tuesday.setColumnCount(1)
        self.t_tuesday.setRowCount(7)
        item = QtWidgets.QTableWidgetItem()
        self.t_tuesday.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.t_tuesday.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.t_tuesday.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.t_tuesday.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.t_tuesday.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.t_tuesday.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.t_tuesday.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.t_tuesday.setHorizontalHeaderItem(0, item)
        self.t_wednesday = QtWidgets.QTableWidget(self.tab_lessons)
        self.t_wednesday.setGeometry(QtCore.QRect(580, 70, 151, 192))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.t_wednesday.sizePolicy().hasHeightForWidth())
        self.t_wednesday.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.t_wednesday.setFont(font)
        self.t_wednesday.setMouseTracking(False)
        self.t_wednesday.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.t_wednesday.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.t_wednesday.setObjectName("t_wednesday")
        self.t_wednesday.setColumnCount(1)
        self.t_wednesday.setRowCount(7)
        item = QtWidgets.QTableWidgetItem()
        self.t_wednesday.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.t_wednesday.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.t_wednesday.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.t_wednesday.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.t_wednesday.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.t_wednesday.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.t_wednesday.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.t_wednesday.setHorizontalHeaderItem(0, item)
        self.t_thursday = QtWidgets.QTableWidget(self.tab_lessons)
        self.t_thursday.setGeometry(QtCore.QRect(60, 300, 151, 192))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.t_thursday.sizePolicy().hasHeightForWidth())
        self.t_thursday.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.t_thursday.setFont(font)
        self.t_thursday.setMouseTracking(False)
        self.t_thursday.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.t_thursday.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.t_thursday.setObjectName("t_thursday")
        self.t_thursday.setColumnCount(1)
        self.t_thursday.setRowCount(7)
        item = QtWidgets.QTableWidgetItem()
        self.t_thursday.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.t_thursday.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.t_thursday.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.t_thursday.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.t_thursday.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.t_thursday.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.t_thursday.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.t_thursday.setHorizontalHeaderItem(0, item)
        self.t_friday = QtWidgets.QTableWidget(self.tab_lessons)
        self.t_friday.setGeometry(QtCore.QRect(320, 300, 151, 192))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.t_friday.sizePolicy().hasHeightForWidth())
        self.t_friday.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.t_friday.setFont(font)
        self.t_friday.setMouseTracking(False)
        self.t_friday.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.t_friday.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.t_friday.setObjectName("t_friday")
        self.t_friday.setColumnCount(1)
        self.t_friday.setRowCount(7)
        item = QtWidgets.QTableWidgetItem()
        self.t_friday.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.t_friday.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.t_friday.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.t_friday.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.t_friday.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.t_friday.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.t_friday.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.t_friday.setHorizontalHeaderItem(0, item)
        self.t_saturday = QtWidgets.QTableWidget(self.tab_lessons)
        self.t_saturday.setGeometry(QtCore.QRect(580, 300, 151, 192))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.t_saturday.sizePolicy().hasHeightForWidth())
        self.t_saturday.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.t_saturday.setFont(font)
        self.t_saturday.setMouseTracking(False)
        self.t_saturday.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.t_saturday.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.t_saturday.setObjectName("t_saturday")
        self.t_saturday.setColumnCount(1)
        self.t_saturday.setRowCount(7)
        item = QtWidgets.QTableWidgetItem()
        self.t_saturday.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.t_saturday.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.t_saturday.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.t_saturday.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.t_saturday.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.t_saturday.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.t_saturday.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.t_saturday.setHorizontalHeaderItem(0, item)
        self.important_ = QtWidgets.QPushButton(self.tab_lessons)
        self.important_.setGeometry(QtCore.QRect(190, 510, 141, 23))
        self.important_.setObjectName("important_")
        self.important_1 = QtWidgets.QPushButton(self.tab_lessons)
        self.important_1.setGeometry(QtCore.QRect(450, 510, 141, 23))
        self.important_1.setObjectName("important_1")
        self.tabWidget.addTab(self.tab_lessons, "")
        self.tab_keys = QtWidgets.QWidget()
        self.tab_keys.setObjectName("tab_keys")
        self.l_books = QtWidgets.QLabel(self.tab_keys)
        self.l_books.setGeometry(QtCore.QRect(0, 0, 400, 80))
        self.l_books.setObjectName("l_books")
        self.l_gdz = QtWidgets.QLabel(self.tab_keys)
        self.l_gdz.setGeometry(QtCore.QRect(400, 0, 400, 80))
        self.l_gdz.setObjectName("l_gdz")
        self.t_books = QtWidgets.QTableWidget(self.tab_keys)
        self.t_books.setGeometry(QtCore.QRect(0, 80, 400, 371))
        self.t_books.setObjectName("t_books")
        self.t_books.setColumnCount(0)
        self.t_books.setRowCount(0)
        self.t_gdz = QtWidgets.QTableWidget(self.tab_keys)
        self.t_gdz.setGeometry(QtCore.QRect(400, 80, 400, 371))
        self.t_gdz.setObjectName("t_gdz")
        self.t_gdz.setColumnCount(0)
        self.t_gdz.setRowCount(0)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.tab_keys)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(-1, 460, 791, 80))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.add_ = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.add_.setObjectName("add_")
        self.horizontalLayout_2.addWidget(self.add_)
        self.open_ = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.open_.setObjectName("open_")
        self.horizontalLayout_2.addWidget(self.open_)
        self.delete_1 = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.delete_1.setObjectName("delete_1")
        self.horizontalLayout_2.addWidget(self.delete_1)
        self.tabWidget.addTab(self.tab_keys, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.middle.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:72pt;\">0.0</span></p></body></html>"))
        self._5.setText(_translate("MainWindow", "5"))
        self._4.setText(_translate("MainWindow", "4"))
        self._3.setText(_translate("MainWindow", "3"))
        self._2.setText(_translate("MainWindow", "2"))
        self._1.setText(_translate("MainWindow", "1"))
        self.list.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><br/></p></body></html>"))
        self.clear_.setText(_translate("MainWindow", "Очистить"))
        self.delete_.setText(_translate("MainWindow", "Стереть"))
        self.save_.setText(_translate("MainWindow", "Сохранить"))
        self.import_.setText(_translate("MainWindow", "Импортировать"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_mid), _translate("MainWindow", "Средний бал"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt;\">Сегодня</span></p></body></html>"))
        self.l_monday.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">Понедельник</p><p align=\"center\"><br/></p></body></html>"))
        self.l_tuesday.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">Вторник</p></body></html>"))
        self.l_wednesday.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">Среда</p></body></html>"))
        self.l_thursday.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">Четверг</p></body></html>"))
        self.l_friday.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">Пятница</p></body></html>"))
        self.l_saturday.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">Суббота</p></body></html>"))
        item = self.t_monday.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "1"))
        item = self.t_monday.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "2"))
        item = self.t_monday.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "3"))
        item = self.t_monday.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "4"))
        item = self.t_monday.verticalHeaderItem(4)
        item.setText(_translate("MainWindow", "5"))
        item = self.t_monday.verticalHeaderItem(5)
        item.setText(_translate("MainWindow", "6"))
        item = self.t_monday.verticalHeaderItem(6)
        item.setText(_translate("MainWindow", "Доп."))
        item = self.t_monday.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Предмет"))
        item = self.t_tuesday.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "1"))
        item = self.t_tuesday.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "2"))
        item = self.t_tuesday.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "3"))
        item = self.t_tuesday.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "4"))
        item = self.t_tuesday.verticalHeaderItem(4)
        item.setText(_translate("MainWindow", "5"))
        item = self.t_tuesday.verticalHeaderItem(5)
        item.setText(_translate("MainWindow", "6"))
        item = self.t_tuesday.verticalHeaderItem(6)
        item.setText(_translate("MainWindow", "Доп."))
        item = self.t_tuesday.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Предмет"))
        item = self.t_wednesday.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "1"))
        item = self.t_wednesday.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "2"))
        item = self.t_wednesday.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "3"))
        item = self.t_wednesday.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "4"))
        item = self.t_wednesday.verticalHeaderItem(4)
        item.setText(_translate("MainWindow", "5"))
        item = self.t_wednesday.verticalHeaderItem(5)
        item.setText(_translate("MainWindow", "6"))
        item = self.t_wednesday.verticalHeaderItem(6)
        item.setText(_translate("MainWindow", "Доп."))
        item = self.t_wednesday.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Предмет"))
        item = self.t_thursday.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "1"))
        item = self.t_thursday.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "2"))
        item = self.t_thursday.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "3"))
        item = self.t_thursday.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "4"))
        item = self.t_thursday.verticalHeaderItem(4)
        item.setText(_translate("MainWindow", "5"))
        item = self.t_thursday.verticalHeaderItem(5)
        item.setText(_translate("MainWindow", "6"))
        item = self.t_thursday.verticalHeaderItem(6)
        item.setText(_translate("MainWindow", "Доп."))
        item = self.t_thursday.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Предмет"))
        item = self.t_friday.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "1"))
        item = self.t_friday.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "2"))
        item = self.t_friday.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "3"))
        item = self.t_friday.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "4"))
        item = self.t_friday.verticalHeaderItem(4)
        item.setText(_translate("MainWindow", "5"))
        item = self.t_friday.verticalHeaderItem(5)
        item.setText(_translate("MainWindow", "6"))
        item = self.t_friday.verticalHeaderItem(6)
        item.setText(_translate("MainWindow", "Доп."))
        item = self.t_friday.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Предмет"))
        item = self.t_saturday.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "1"))
        item = self.t_saturday.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "2"))
        item = self.t_saturday.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "3"))
        item = self.t_saturday.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "4"))
        item = self.t_saturday.verticalHeaderItem(4)
        item.setText(_translate("MainWindow", "5"))
        item = self.t_saturday.verticalHeaderItem(5)
        item.setText(_translate("MainWindow", "6"))
        item = self.t_saturday.verticalHeaderItem(6)
        item.setText(_translate("MainWindow", "Доп."))
        item = self.t_saturday.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Предмет"))
        self.important_.setText(_translate("MainWindow", "Важные"))
        self.important_1.setText(_translate("MainWindow", "Изменить"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_lessons), _translate("MainWindow", "Расписание"))
        self.l_books.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">Учебники и другие пособия</p></body></html>"))
        self.l_gdz.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">ГДЗ</p></body></html>"))
        self.add_.setText(_translate("MainWindow", "Добавить/Изменить"))
        self.open_.setText(_translate("MainWindow", "Открыть"))
        self.delete_1.setText(_translate("MainWindow", "Удалить"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_keys), _translate("MainWindow", "Ссылки"))
